### ISSUE TITLE
Can requirements.txt be provided? There are too much environmental issues when I am running, thanks very much!!

### ISSUE THREAD

**Issue by liaozengxi** [vndee/local-rag-example#1]

**Comment by vndee** [comment]
Hi @liaozengxi, basically you only need langchain and streamlit as following:
```bash
pip install langchain streamlit
```
I've updated README file also, thanks for your comment.

**Comment by krsmes** [comment]
you need 
`pip install langchain streamlit streamlit_chat pypdf fastembed chromadb`
at minimum

**Comment by xianshenglu** [comment]
I used `pip install  --force-reinstall langchain==^0.1.12 streamlit-chat==^0.1.1 pypdf==^3.17.1 fastembed==^0.2.4 openai==^1.3.6 langchainhub==^0.1.14 chromadb==^0.4.18 streamlit==^1.29.0 watchdog==^3.0.0 langchain_community cryptography`.
