### ISSUE TITLE
AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by hashmint** [vndee/local-rag-example#10]
Failed to load resource: the server responded with a status of 403 (Forbidden) - on file upload in StreamLit
<img width="1440" alt="Screenshot 2024-05-28 at 13 51 01" src="https://github.com/vndee/local-rag-example/assets/171005778/040551c6-2484-482a-8d3f-80f034467fcc">

**Comment by vndee** [comment]
Hey, can you try upgrade the streamlit package?
