### ISSUE TITLE
ingestion

### ISSUE THREAD

**Issue by kunwar1908** [vndee/local-rag-example#11]
i'm facing an ingestion issue where when we try to upload the file in our UI application , the backend code stops down . chunks get created , embeddings too , embedding model called , vector store initiated too but after it the code stops , i tried reinstalling packages too but no change , even with the same code as given

**Comment by jalejandro0211** [comment]
Same with me, do you have a solution?

**Comment by vndee** [comment]
Thanks @kunwar1908, I will update this project to the latest best practice next-week. It will solve your issue.

**Comment by vndee** [comment]
Hey @kunwar1908 @jalejandro0211, please check the latest code. I believe it now solve your issue.

**Comment by kunwar1908** [comment]
> Hey @kunwar1908 @jalejandro0211, please check the latest code. I believe it now solve your issue.

thanks a lot , the issue's been resolved by your change that was done , gratitude ❤️
![image](https://github.com/user-attachments/assets/444de0ff-2b56-4a77-aa93-ea36b0d5d7f4)
