### ISSUE TITLE
No context message

### ISSUE THREAD

**Issue by deedeetype** [vndee/local-rag-example#6]
I'm always getting the following message from the bot:  I'm an assistant for answering questions. I don't have enough context to identify "it". Please provide more information.

No matter which PDF document I load or the question I ask.

Ollama server is running well, all the previous steps are working, but the bot doesn't seem able to chat on the document I loaded.

**Comment by heliocarbex** [comment]
You have to use the name of the document. If you upload "test.pdf" you must ask something like "summarize test.pdf".

**Comment by vndee** [comment]
Can you share your question for the bot, does it relate to the uploaded file?
