### ISSUE TITLE
ValidationError: 1 validation error for FastEmbedEmbeddings

### ISSUE THREAD

**Issue by Mixddux** [vndee/local-rag-example#8]
<img width="722" alt="Screen Shot 2024-05-05 at 9 14 42 AM" src="https://github.com/vndee/local-rag-example/assets/31517590/e178602e-cfbb-4cd9-b1fb-7cb0a6fca9bb">
When I first build the model, it worked fine. The next day, I am trying to run it again and while trying to upload a PDF, by dragging and browsing, I receive the following error:

ValidationError: 1 validation error for FastEmbedEmbeddings __root__ Could not find model.onnx in /var/folders/t6/1rfncxtx1v5g_d4tmt1rfpqm0000gn/T/fastembed_cache/fast-bge-small-en-v1.5 (type=value_error)

How can I rectify the error?

**Comment by vndee** [comment]
Did you try to remove and re-install FastEmbed. I believe this issue related to the fastembed library: https://github.com/qdrant/fastembed
