### ISSUE TITLE
Question: How do you see intermediate steps?

### ISSUE THREAD

**Issue by ambrose-leung** [vndee/local-rag-example#9]
More of a Langchain question - Can you show us how to view which chunks are being returned and the corresponding relevancy score?

But I can't figure out how to do this as a lot of the actual logic/application flow is abstracted away.

Thank you!

**Comment by vndee** [comment]
I have add `set_debug` and `set_verbose` method to the code, please check the latest code in the repository.

**Comment by vndee** [comment]
Close due to inactivity
